(load "lib/ssl.scm")
(load "lib/socket.scm")
(load "lib/string.scm")
(load "lib/bytes.scm")
(load "lib/stdout.scm")

(let* ((scheme "https")
       (host "raw.githubusercontent.com")
       (port 443)
       (path "/yoanncouillec/lispweb.ml/master/lib/list.scm"))
  (ssl-init)
  (let* ((he (gethostbyname host))
	 (sockaddr (addr_inet (inet_addr_of_host_entry he) port))
	 (ssl (ssl-open-connection (ssl-protocol-v23) sockaddr))
	 (cert (ssl-get-certificate ssl))
	 (cipher (ssl-get-cipher ssl))
	 (issuer(ssl-get-issuer cert))
	 (subject (ssl-get-subject cert))
	 (cipher_name (ssl-get-cipher-name cipher))
	 (cipher_version (ssl-get-cipher-version cipher))
	 (cipher_description (ssl-get-cipher-description cipher))
	 (s (concat "" (list "GET " path " HTTP/1.1" (make-string 1 '\n') "Host: " host (make-string 1 '\n') (make-string 1 '\n'))))
	 (b (bytes-of-string s))
	 (bufsize 1024)
	 (buff (bytes-create bufsize)))
    (ssl-write ssl b 0 (bytes-length b))
    (let* ((r (ssl-read ssl buff 0 bufsize))
	   (s (bytes-to-string buff)))
      (print-line s))))
