(define bootstrap-badge-primary   (lambda (s) (<span> (list (list "class" "badge badge-primary")) (list (list "string" s)))))
(define bootstrap-badge-secondary (lambda (s) (<span> (list (list "class" "badge badge-secondary")) (list (list "string" s)))))
(define bootstrap-badge-success   (lambda (s) (<span> (list (list "class" "badge badge-success")) (list (list "string" s)))))
(define bootstrap-badge-danger    (lambda (s) (<span> (list (list "class" "badge badge-danger")) (list (list "string" s)))))
(define bootstrap-badge-warning   (lambda (s) (<span> (list (list "class" "badge badge-warning")) (list (list "string" s)))))
(define bootstrap-badge-info      (lambda (s) (<span> (list (list "class" "badge badge-info")) (list (list "string" s)))))
(define bootstrap-badge-light     (lambda (s) (<span> (list (list "class" "badge badge-light")) (list (list "string" s)))))
(define bootstrap-badge-dark      (lambda (s) (<span> (list (list "class" "badge badge-dark")) (list (list "string" s)))))

(define bootstrap-badge-pill-primary   (lambda (s) (<span> (list (list "class" "badge badge-pill badge-primary")) (list (list "string" s)))))
(define bootstrap-badge-pill-secondary (lambda (s) (<span> (list (list "class" "badge badge-pill badge-secondary")) (list (list "string" s)))))
(define bootstrap-badge-pill-success   (lambda (s) (<span> (list (list "class" "badge badge-pill badge-success")) (list (list "string" s)))))
(define bootstrap-badge-pill-danger    (lambda (s) (<span> (list (list "class" "badge badge-pill badge-danger")) (list (list "string" s)))))
(define bootstrap-badge-pill-warning   (lambda (s) (<span> (list (list "class" "badge badge-pill badge-warning")) (list (list "string" s)))))
(define bootstrap-badge-pill-info      (lambda (s) (<span> (list (list "class" "badge badge-pill badge-info")) (list (list "string" s)))))
(define bootstrap-badge-pill-light     (lambda (s) (<span> (list (list "class" "badge badge-pill badge-light")) (list (list "string" s)))))
(define bootstrap-badge-pill-dark      (lambda (s) (<span> (list (list "class" "badge badge-pill badge-dark")) (list (list "string" s)))))

(define bootstrap-badge-link-primary   (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-primary")) (list (list "string" s)))))
(define bootstrap-badge-link-secondary (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-secondary")) (list (list "string" s)))))
(define bootstrap-badge-link-success   (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-success")) (list (list "string" s)))))
(define bootstrap-badge-link-danger    (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-danger")) (list (list "string" s)))))
(define bootstrap-badge-link-warning   (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-warning")) (list (list "string" s)))))
(define bootstrap-badge-link-info      (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-info")) (list (list "string" s)))))
(define bootstrap-badge-link-light     (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-light")) (list (list "string" s)))))
(define bootstrap-badge-link-dark      (lambda (s href) (<a> (list (list "href" href) (list "class" "badge badge-dark")) (list (list "string" s)))))
