(load "lib/file.scm")
(load "lib/http.scm")
(load "lib/string.scm")

(define service
  (lambda (out method path protocol headers)
    (if (equal? path "/")
	(let* ((content "<h1>Welcome to LispWeb Server 1.0<h1>"))
	  (output-string out "HTTP/1.1 200 OK")
	  (output-char out '\n')
	  (output-string out "Content-Length: ")
	  (output-string out (int->string (string-length content)))
	  (output-char out '\n')
	  (output-string out "Content-Type: text/html")
	  (output-char out '\n')
	  (output-char out '\n')
	  (output-string out content))
	(output-string out ""))
    (flush out)))

(http-server 8080 service)
