name: Lispw

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Opam
        run: |
          sudo apt update
          sudo apt install opam
          opam init
          opam install dune
          eval $(opam env)
      - name: Build Lispw
        run: |
          dune build
