name: Lispw

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
      - run: opam install . --deps-only --with-test
      - run: opam install ISO8601
      - run: opam install core
      - run: opam install ssl
      - run: opam install ANSITerminal
      - run: opam install menhir
      - run: opam install alcotest        
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
