name: Lispw

on:
  push:
    branches: master

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Opam
        run: sudo apt install opam
      - name: Install Dune
        run: opam install dune
